# Day 53

#### NumPy Built-In modules Day 3

In [1]:
import numpy as np

a = np.arange(6).reshape(3,2)
print(a)

# Array View
b = a.view()
print(b)

# Array Copy
c = b.copy()    
print(c)


# Shape of an Array
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)              
print(arr.shape)

x = a,b,c.shape
print(x)

[[0 1]
 [2 3]
 [4 5]]
[[0 1]
 [2 3]
 [4 5]]
[[0 1]
 [2 3]
 [4 5]]
[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)
(array([[0, 1],
       [2, 3],
       [4, 5]]), array([[0, 1],
       [2, 3],
       [4, 5]]), (3, 2))
