# Day 55

#### NumPy Built-In modules Day 5

In [1]:
import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

# Splitting NumPy Arrays
splarr = np.array_split(arr, 2, axis=2)
print(splarr)

# Split Into Arrays
print(splarr[0])
print(splarr[1])

# Searching Arrays
x = np.where(arr == 4)
print(x)

y = np.where(arr%2 == 1)
print(y)

# Search Sorted
arr = np.array([1,2,3])
z = np.searchsorted(arr, 3)

print(z)

[array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]]), array([[[ 3],
        [ 6]],

       [[ 9],
        [12]]])]
[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]
[[[ 3]
  [ 6]]

 [[ 9]
  [12]]]
(array([0], dtype=int64), array([1], dtype=int64), array([0], dtype=int64))
(array([0, 0, 0, 1, 1, 1], dtype=int64), array([0, 0, 1, 0, 0, 1], dtype=int64), array([0, 2, 1, 0, 2, 1], dtype=int64))
2
