# Day 57

#### NumPy Built-In modules Day 6

In [1]:
from numpy import random

arr = random.choice([5,6,7,9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
print(arr)

arr = random.binomial(n=10, p=0.6, size=100)
print(arr)

# Normal Distribution
x = random.normal(size=(3,5))
print(x)

[7 6 7 7 7 6 5 7 6 7 6 7 5 7 7 6 7 7 5 6 7 7 7 7 7 6 7 7 7 7 6 7 7 7 7 7 7
 5 7 7 6 7 6 5 7 7 7 6 7 7 7 7 7 7 7 7 6 7 7 5 7 7 5 6 6 6 6 7 7 7 7 5 7 6
 7 5 7 7 7 5 5 7 7 7 7 7 7 6 6 5 6 7 6 7 6 5 6 6 6 7]
[7 6 7 5 6 4 5 5 6 8 7 8 7 4 7 7 9 4 7 7 4 6 4 5 7 4 7 7 8 6 4 7 6 5 5 4 8
 7 5 4 8 6 6 7 8 9 8 6 5 7 7 1 5 4 3 7 7 6 6 7 7 9 8 7 4 7 5 5 5 6 6 6 7 5
 7 3 5 7 7 5 7 7 6 6 6 5 8 5 6 4 8 6 3 9 5 4 6 7 8 7]
[[ 0.17182979 -0.94964512  0.57546989  0.9395263  -0.30758925]
 [-0.18358362  0.34420031 -1.18776505 -0.69640227  2.36015498]
 [ 1.66132755  1.52165154 -0.06155209  0.48171222 -0.69676123]]
