# Day 58

#### NumPy Built-In modules Day 8

In [1]:
from numpy import random

x = random.uniform(size=(2, 3))
print(x)                        # Uniform Distribution

y = random.poisson(lam=2, size=10)
print(y)                        # Poisson Distribution

z = random.binomial(n=10, p=1, size=10)
print(z)                        # Binomial Distribution

a = random.pareto(a=2, size=(2, 3))
print(a)                        # Pareto Distribution

b = random.zipf(a=2, size=(2, 3))
print(b)                        # Zipf Distribution

[[0.6563073  0.98617453 0.89084219]
 [0.51002854 0.65265137 0.70086613]]
[3 4 2 7 0 1 1 0 2 1]
[10 10 10 10 10 10 10 10 10 10]
[[0.63448614 0.50109021 1.72913291]
 [0.86263133 0.16903457 0.1559547 ]]
[[1 1 9]
 [1 1 1]]
