# Day 54

#### NumPy Built-In modules Day 4

In [1]:
import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for a in arr:
    print(a)

# 
for x in np.nditer(arr):
    print(x)

# Iterating Array With Different Data Types
for y in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(y)

# Enumerated Iteration Using ndenumerate()
for nuId, z in np.ndenumerate(arr):
    print(nuId, z)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12
b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
b'11'
b'12'
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12
